package org.piramalswasthya.sakhi.model

data class FPOTCache (
    var monthlySerialNumber: String? = null,
    var annualSerialNumber: String? = null,
    var spouseName: String? = null,
    var category: String? = null,
    var benAddress: String? = null,
    var contactNumber: String? = null,
    var educationalQualification: String? = null,
    var numChildren: String? = null,
    var youngestChildAge: String? = null,
    var sterilization: Boolean? = null,
    var mrCheckListFilled: Boolean? = null,
    var dateOfOperation: Long = 0,
    var femaleSterilization: String? = null,
    var secondFollowUpExpectedDate: Long = 0,
    var followUpActualDate: Long = 0,
    var followUpDetails: String? = null,
    var secondPostFollowUpCounselling: String? = null,
    var thirdFollowUpExpectedDate: Long = 0,
    var menstruationStarted: Boolean? = null,
    var spermatozoaFoundInSemen: String? = null,
    var thirdPostFollowUpCounselling: String? = null,
    var sterilizationOrVasectomyIssueDate: Long = 0,
    var notIssuedReason: String? = null,
    var sterilizationOrVasectomyDocSubmitted: String? = null,
    var remarks: String? = null,
)