name: Android Build and Distribute

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  main_project_module: app
  repository_name: FLW-Mobile-App
  date_today: ${{ github.event.head_commit.timestamp }}


jobs:
  saksham_stag_job:
    runs-on: ubuntu-latest

    environment: SAKSHAM_STAG

    strategy:
      matrix:
        variant: [ SakshamStagDebug ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r27c
          link-to-sdk: true

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.31.1'

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Verify Ruby installation
        run: ruby -v

      - name: Decode google-services.json from secret
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }} | base64 --decode > ./app/google-services.json
      #          echo "Decoded google-services.json"
      #          cat ./app/google-services.json

      - name: Decode GoogleServiceAccount.json from secret
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }} | base64 --decode > ./fastlane/GoogleServiceAccount.json
      #          echo "Decoded GoogleServiceAccount.json"
      #          cat ./fastlane/GoogleServiceAccount.json

      - name: Set Environment Variables
        run: |
          echo "ENCRYPTED_PASS_KEY=${{ secrets.ENCRYPTED_PASS_KEY }}" >> $GITHUB_ENV
          echo "ABHA_CLIENT_ID=${{ secrets.ABHA_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ABHA_CLIENT_SECRET=${{ secrets.ABHA_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "BASE_TMC_URL=${{ secrets.BASE_TMC_URL }}" >> $GITHUB_ENV
          echo "BASE_ABHA_URL=${{ secrets.BASE_ABHA_URL }}" >> $GITHUB_ENV
          echo "ABHA_TOKEN_URL=${{ secrets.ABHA_TOKEN_URL }}" >> $GITHUB_ENV
          echo "ABHA_AUTH_URL=${{ secrets.ABHA_AUTH_URL }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" > $GITHUB_ENV
          echo "FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> $GITHUB_ENV

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      #      - name: Verify `local.properties` Content
      #        run: |
      #          echo "Contents of local.properties:"
      #          cat ./local.properties


      - name: Build and Distribute app to Firebase
        run: bundle exec fastlane android build_and_distribute_apk_to_firebase variant:${{ matrix.variant }}

      - name: List APK files
        run: |
          echo "Listing sakshamStag APK files:"
          ls -al app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-armeabi-v7a-debug.apk
          ls -al app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-arm64-v8a-debug.apk
          ls -al app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-x86-debug.apk
          ls -al app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-x86_64-debug.apk
          ls -al app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-universal-debug.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: FLW-Mobile-App - APK(s) ${{ matrix.variant }} generated
          path: |
            app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-armeabi-v7a-debug.apk
            app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-arm64-v8a-debug.apk
            app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-x86-debug.apk
            app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-x86_64-debug.apk
            app/build/outputs/apk/sakshamStag/debug/app-sakshamStag-universal-debug.apk


  saksham_uat_job:
    runs-on: ubuntu-latest
    environment: SAKSHAM_UAT

    strategy:
      matrix:
        variant: [ SakshamUatDebug ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r27c
          link-to-sdk: true

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.31.1'

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Verify Ruby installation
        run: ruby -v

      - name: Decode google-services.json from secret
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }} | base64 --decode > ./app/google-services.json
      #          echo "Decoded google-services.json"
      #          cat ./app/google-services.json

      - name: Decode GoogleServiceAccount.json from secret
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }} | base64 --decode > ./fastlane/GoogleServiceAccount.json
      #          echo "Decoded GoogleServiceAccount.json"
      #          cat ./fastlane/GoogleServiceAccount.json

      - name: Set Environment Variables
        run: |
          echo "ENCRYPTED_PASS_KEY=${{ secrets.ENCRYPTED_PASS_KEY }}" >> $GITHUB_ENV
          echo "ABHA_CLIENT_ID=${{ secrets.ABHA_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ABHA_CLIENT_SECRET=${{ secrets.ABHA_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "BASE_TMC_URL=${{ secrets.BASE_TMC_URL }}" >> $GITHUB_ENV
          echo "BASE_ABHA_URL=${{ secrets.BASE_ABHA_URL }}" >> $GITHUB_ENV
          echo "ABHA_TOKEN_URL=${{ secrets.ABHA_TOKEN_URL }}" >> $GITHUB_ENV
          echo "ABHA_AUTH_URL=${{ secrets.ABHA_AUTH_URL }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" > $GITHUB_ENV
          echo "FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> $GITHUB_ENV

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      #      - name: Verify `local.properties` Content
      #        run: |
      #          echo "Contents of local.properties:"
      #          cat ./local.properties


      - name: Build and Distribute app to Firebase
        run: bundle exec fastlane android build_and_distribute_apk_to_firebase variant:${{ matrix.variant }}

      - name: List APK files
        run: |
          echo "Listing sakshamUat APK files:"
          ls -al app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-armeabi-v7a-debug.apk
          ls -al app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-arm64-v8a-debug.apk
          ls -al app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-x86-debug.apk
          ls -al app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-x86_64-debug.apk
          ls -al app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-universal-debug.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: FLW-Mobile-App - APK(s) ${{ matrix.variant }} generated
          path: |
            app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-armeabi-v7a-debug.apk
            app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-arm64-v8a-debug.apk
            app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-x86-debug.apk
            app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-x86_64-debug.apk
            app/build/outputs/apk/sakshamUat/debug/app-sakshamUat-universal-debug.apk
