name: Android Build and Distribute

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  main_project_module: app
  repository_name: FLW-Mobile-App
  date_today: ${{ github.event.head_commit.timestamp }}

jobs:
  saksham_stag_job:
    uses: ./.github/workflows/build-distribute.yml
    with:
      environment: SAKSHAM_STAG
      variant: SakshamStag
      build_type: debug
    secrets: inherit

  saksham_uat_job:
    uses: ./.github/workflows/build-distribute.yml
    with:
      environment: SAKSHAM_UAT
      variant: SakshamUat
      build_type: debug
    secrets: inherit

  niramay_production_job:
    uses: ./.github/workflows/build-distribute.yml
    with:
      environment: NIRAMAY_PRODUCTION
      variant: Niramay
      build_type: release
    secrets: inherit

  xushrukha_production_job:
    uses: ./.github/workflows/build-distribute.yml
    with:
      environment: XUSHRUKHA_PRODUCTION
      variant: Xushrukha
      build_type: release
    secrets: inherit

   


